package model;
// Generated May 24, 2016 9:30:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoNomina generated by hbm2java
 */
public class EstadoNomina  implements java.io.Serializable {


     private int id;
     private String estado;
     private Set pagos = new HashSet(0);
     private Set endosos = new HashSet(0);

    public EstadoNomina() {
    }

	
    public EstadoNomina(int id, String estado) {
        this.id = id;
        this.estado = estado;
    }
    public EstadoNomina(int id, String estado, Set pagos, Set endosos) {
       this.id = id;
       this.estado = estado;
       this.pagos = pagos;
       this.endosos = endosos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }
    public Set getEndosos() {
        return this.endosos;
    }
    
    public void setEndosos(Set endosos) {
        this.endosos = endosos;
    }




}


