package model;
// Generated May 24, 2016 9:30:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MetodoPago generated by hbm2java
 */
public class MetodoPago  implements java.io.Serializable {


     private int id;
     private String metodo;
     private Set datosPagos = new HashSet(0);
     private Set asistencias = new HashSet(0);

    public MetodoPago() {
    }

	
    public MetodoPago(int id) {
        this.id = id;
    }
    public MetodoPago(int id, String metodo, Set datosPagos, Set asistencias) {
       this.id = id;
       this.metodo = metodo;
       this.datosPagos = datosPagos;
       this.asistencias = asistencias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMetodo() {
        return this.metodo;
    }
    
    public void setMetodo(String metodo) {
        this.metodo = metodo;
    }
    public Set getDatosPagos() {
        return this.datosPagos;
    }
    
    public void setDatosPagos(Set datosPagos) {
        this.datosPagos = datosPagos;
    }
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }




}


