package model;
// Generated May 24, 2016 9:30:39 AM by Hibernate Tools 4.3.1



/**
 * ModalPyme generated by hbm2java
 */
public class ModalPyme  implements java.io.Serializable {


     private int id;
     private AreaEjecutivo areaEjecutivo;
     private Solicitud solicitud;
     private String empresa;
     private String giro;

    public ModalPyme() {
    }

    public ModalPyme(int id, AreaEjecutivo areaEjecutivo, Solicitud solicitud, String empresa, String giro) {
       this.id = id;
       this.areaEjecutivo = areaEjecutivo;
       this.solicitud = solicitud;
       this.empresa = empresa;
       this.giro = giro;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public AreaEjecutivo getAreaEjecutivo() {
        return this.areaEjecutivo;
    }
    
    public void setAreaEjecutivo(AreaEjecutivo areaEjecutivo) {
        this.areaEjecutivo = areaEjecutivo;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getGiro() {
        return this.giro;
    }
    
    public void setGiro(String giro) {
        this.giro = giro;
    }




}


