package model;
// Generated May 24, 2016 9:30:39 AM by Hibernate Tools 4.3.1



/**
 * ModalAsistencia generated by hbm2java
 */
public class ModalAsistencia  implements java.io.Serializable {


     private int id;
     private AreaEjecutivo areaEjecutivo;
     private Solicitud solicitud;
     private Integer edad;

    public ModalAsistencia() {
    }

	
    public ModalAsistencia(int id) {
        this.id = id;
    }
    public ModalAsistencia(int id, AreaEjecutivo areaEjecutivo, Solicitud solicitud, Integer edad) {
       this.id = id;
       this.areaEjecutivo = areaEjecutivo;
       this.solicitud = solicitud;
       this.edad = edad;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public AreaEjecutivo getAreaEjecutivo() {
        return this.areaEjecutivo;
    }
    
    public void setAreaEjecutivo(AreaEjecutivo areaEjecutivo) {
        this.areaEjecutivo = areaEjecutivo;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }




}


