package model;
// Generated May 24, 2016 9:30:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pagina generated by hbm2java
 */
public class Pagina  implements java.io.Serializable {


     private int id;
     private Aseguradora aseguradora;
     private Campaña campaña;
     private String url;
     private String descripcion;
     private int estatus;
     private Date fechaRegistro;
     private Date fechaActualizacion;
     private Date fechaUltimoCorte;
     private Set solicituds = new HashSet(0);
     private Set costoses = new HashSet(0);

    public Pagina() {
    }

	
    public Pagina(int id, Aseguradora aseguradora, Campaña campaña, String url, int estatus) {
        this.id = id;
        this.aseguradora = aseguradora;
        this.campaña = campaña;
        this.url = url;
        this.estatus = estatus;
    }
    public Pagina(int id, Aseguradora aseguradora, Campaña campaña, String url, String descripcion, int estatus, Date fechaRegistro, Date fechaActualizacion, Date fechaUltimoCorte, Set solicituds, Set costoses) {
       this.id = id;
       this.aseguradora = aseguradora;
       this.campaña = campaña;
       this.url = url;
       this.descripcion = descripcion;
       this.estatus = estatus;
       this.fechaRegistro = fechaRegistro;
       this.fechaActualizacion = fechaActualizacion;
       this.fechaUltimoCorte = fechaUltimoCorte;
       this.solicituds = solicituds;
       this.costoses = costoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Aseguradora getAseguradora() {
        return this.aseguradora;
    }
    
    public void setAseguradora(Aseguradora aseguradora) {
        this.aseguradora = aseguradora;
    }
    public Campaña getCampaña() {
        return this.campaña;
    }
    
    public void setCampaña(Campaña campaña) {
        this.campaña = campaña;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(int estatus) {
        this.estatus = estatus;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Date getFechaUltimoCorte() {
        return this.fechaUltimoCorte;
    }
    
    public void setFechaUltimoCorte(Date fechaUltimoCorte) {
        this.fechaUltimoCorte = fechaUltimoCorte;
    }
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }
    public Set getCostoses() {
        return this.costoses;
    }
    
    public void setCostoses(Set costoses) {
        this.costoses = costoses;
    }




}


