package model;
// Generated May 24, 2016 9:30:39 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int idPago;
     private Aseguradora aseguradora;
     private DatosPago datosPago;
     private EstadoNomina estadoNomina;
     private Nomina nomina;
     private Usuario usuario;
     private BigDecimal cantidad;
     private Date fecha;
     private Date fechaPago;
     private Integer aplicado;
     private String numPoliza;
     private Date fechaInicio;
     private String comentarios;
     private Byte seriePago;
     private Integer aplicadoRen;

    public Pago() {
    }

	
    public Pago(int idPago, DatosPago datosPago, EstadoNomina estadoNomina, Nomina nomina, Usuario usuario, BigDecimal cantidad, String comentarios) {
        this.idPago = idPago;
        this.datosPago = datosPago;
        this.estadoNomina = estadoNomina;
        this.nomina = nomina;
        this.usuario = usuario;
        this.cantidad = cantidad;
        this.comentarios = comentarios;
    }
    public Pago(int idPago, Aseguradora aseguradora, DatosPago datosPago, EstadoNomina estadoNomina, Nomina nomina, Usuario usuario, BigDecimal cantidad, Date fecha, Date fechaPago, Integer aplicado, String numPoliza, Date fechaInicio, String comentarios, Byte seriePago, Integer aplicadoRen) {
       this.idPago = idPago;
       this.aseguradora = aseguradora;
       this.datosPago = datosPago;
       this.estadoNomina = estadoNomina;
       this.nomina = nomina;
       this.usuario = usuario;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.fechaPago = fechaPago;
       this.aplicado = aplicado;
       this.numPoliza = numPoliza;
       this.fechaInicio = fechaInicio;
       this.comentarios = comentarios;
       this.seriePago = seriePago;
       this.aplicadoRen = aplicadoRen;
    }
   
    public int getIdPago() {
        return this.idPago;
    }
    
    public void setIdPago(int idPago) {
        this.idPago = idPago;
    }
    public Aseguradora getAseguradora() {
        return this.aseguradora;
    }
    
    public void setAseguradora(Aseguradora aseguradora) {
        this.aseguradora = aseguradora;
    }
    public DatosPago getDatosPago() {
        return this.datosPago;
    }
    
    public void setDatosPago(DatosPago datosPago) {
        this.datosPago = datosPago;
    }
    public EstadoNomina getEstadoNomina() {
        return this.estadoNomina;
    }
    
    public void setEstadoNomina(EstadoNomina estadoNomina) {
        this.estadoNomina = estadoNomina;
    }
    public Nomina getNomina() {
        return this.nomina;
    }
    
    public void setNomina(Nomina nomina) {
        this.nomina = nomina;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }
    public Integer getAplicado() {
        return this.aplicado;
    }
    
    public void setAplicado(Integer aplicado) {
        this.aplicado = aplicado;
    }
    public String getNumPoliza() {
        return this.numPoliza;
    }
    
    public void setNumPoliza(String numPoliza) {
        this.numPoliza = numPoliza;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public Byte getSeriePago() {
        return this.seriePago;
    }
    
    public void setSeriePago(Byte seriePago) {
        this.seriePago = seriePago;
    }
    public Integer getAplicadoRen() {
        return this.aplicadoRen;
    }
    
    public void setAplicadoRen(Integer aplicadoRen) {
        this.aplicadoRen = aplicadoRen;
    }




}


