package model;
// Generated May 24, 2016 9:30:39 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private int idSolicitud;
     private Campaña campaña;
     private EstadoSolicitud estadoSolicitud;
     private Pagina pagina;
     private Usuario usuario;
     private String nombre;
     private String telefono;
     private String correo;
     private String cp;
     private Date anio;
     private String marca;
     private String modelo;
     private String cve;
     private String cobertura;
     private BigDecimal primaTotal;
     private String comentarios;
     private Date fechaSolicitud;
     private Byte idTipoContacto;
     private Date fechaNacimiento;
     private char sexo;
     private Set modalPymes = new HashSet(0);
     private Set modalGastosMedicoses = new HashSet(0);
     private Set modalSeguroDeVidas = new HashSet(0);
     private Set modalAsistencias = new HashSet(0);
     private Set registros = new HashSet(0);
     private Set modalSeguroDeHogars = new HashSet(0);

    public Solicitud() {
    }

	
    public Solicitud(int idSolicitud, Pagina pagina, Usuario usuario, String cve, String cobertura, BigDecimal primaTotal, Date fechaNacimiento, char sexo) {
        this.idSolicitud = idSolicitud;
        this.pagina = pagina;
        this.usuario = usuario;
        this.cve = cve;
        this.cobertura = cobertura;
        this.primaTotal = primaTotal;
        this.fechaNacimiento = fechaNacimiento;
        this.sexo = sexo;
    }
    public Solicitud(int idSolicitud, Campaña campaña, EstadoSolicitud estadoSolicitud, Pagina pagina, Usuario usuario, String nombre, String telefono, String correo, String cp, Date anio, String marca, String modelo, String cve, String cobertura, BigDecimal primaTotal, String comentarios, Date fechaSolicitud, Byte idTipoContacto, Date fechaNacimiento, char sexo, Set modalPymes, Set modalGastosMedicoses, Set modalSeguroDeVidas, Set modalAsistencias, Set registros, Set modalSeguroDeHogars) {
       this.idSolicitud = idSolicitud;
       this.campaña = campaña;
       this.estadoSolicitud = estadoSolicitud;
       this.pagina = pagina;
       this.usuario = usuario;
       this.nombre = nombre;
       this.telefono = telefono;
       this.correo = correo;
       this.cp = cp;
       this.anio = anio;
       this.marca = marca;
       this.modelo = modelo;
       this.cve = cve;
       this.cobertura = cobertura;
       this.primaTotal = primaTotal;
       this.comentarios = comentarios;
       this.fechaSolicitud = fechaSolicitud;
       this.idTipoContacto = idTipoContacto;
       this.fechaNacimiento = fechaNacimiento;
       this.sexo = sexo;
       this.modalPymes = modalPymes;
       this.modalGastosMedicoses = modalGastosMedicoses;
       this.modalSeguroDeVidas = modalSeguroDeVidas;
       this.modalAsistencias = modalAsistencias;
       this.registros = registros;
       this.modalSeguroDeHogars = modalSeguroDeHogars;
    }
   
    public int getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(int idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Campaña getCampaña() {
        return this.campaña;
    }
    
    public void setCampaña(Campaña campaña) {
        this.campaña = campaña;
    }
    public EstadoSolicitud getEstadoSolicitud() {
        return this.estadoSolicitud;
    }
    
    public void setEstadoSolicitud(EstadoSolicitud estadoSolicitud) {
        this.estadoSolicitud = estadoSolicitud;
    }
    public Pagina getPagina() {
        return this.pagina;
    }
    
    public void setPagina(Pagina pagina) {
        this.pagina = pagina;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public Date getAnio() {
        return this.anio;
    }
    
    public void setAnio(Date anio) {
        this.anio = anio;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getCve() {
        return this.cve;
    }
    
    public void setCve(String cve) {
        this.cve = cve;
    }
    public String getCobertura() {
        return this.cobertura;
    }
    
    public void setCobertura(String cobertura) {
        this.cobertura = cobertura;
    }
    public BigDecimal getPrimaTotal() {
        return this.primaTotal;
    }
    
    public void setPrimaTotal(BigDecimal primaTotal) {
        this.primaTotal = primaTotal;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }
    public Byte getIdTipoContacto() {
        return this.idTipoContacto;
    }
    
    public void setIdTipoContacto(Byte idTipoContacto) {
        this.idTipoContacto = idTipoContacto;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public Set getModalPymes() {
        return this.modalPymes;
    }
    
    public void setModalPymes(Set modalPymes) {
        this.modalPymes = modalPymes;
    }
    public Set getModalGastosMedicoses() {
        return this.modalGastosMedicoses;
    }
    
    public void setModalGastosMedicoses(Set modalGastosMedicoses) {
        this.modalGastosMedicoses = modalGastosMedicoses;
    }
    public Set getModalSeguroDeVidas() {
        return this.modalSeguroDeVidas;
    }
    
    public void setModalSeguroDeVidas(Set modalSeguroDeVidas) {
        this.modalSeguroDeVidas = modalSeguroDeVidas;
    }
    public Set getModalAsistencias() {
        return this.modalAsistencias;
    }
    
    public void setModalAsistencias(Set modalAsistencias) {
        this.modalAsistencias = modalAsistencias;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }
    public Set getModalSeguroDeHogars() {
        return this.modalSeguroDeHogars;
    }
    
    public void setModalSeguroDeHogars(Set modalSeguroDeHogars) {
        this.modalSeguroDeHogars = modalSeguroDeHogars;
    }




}


