package model;
// Generated May 24, 2016 9:30:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPago generated by hbm2java
 */
public class TipoPago  implements java.io.Serializable {


     private int id;
     private String tipo;
     private int cantidadPagos;
     private Set registros = new HashSet(0);

    public TipoPago() {
    }

	
    public TipoPago(int id, String tipo, int cantidadPagos) {
        this.id = id;
        this.tipo = tipo;
        this.cantidadPagos = cantidadPagos;
    }
    public TipoPago(int id, String tipo, int cantidadPagos, Set registros) {
       this.id = id;
       this.tipo = tipo;
       this.cantidadPagos = cantidadPagos;
       this.registros = registros;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public int getCantidadPagos() {
        return this.cantidadPagos;
    }
    
    public void setCantidadPagos(int cantidadPagos) {
        this.cantidadPagos = cantidadPagos;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


