package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AreaEjecutivo generated by hbm2java
 */
@Entity
@Table(name="areaEjecutivo"
    ,catalog="trigarante"
)
public class AreaEjecutivo  implements java.io.Serializable {


     private int id;
     private Area area;
     private Usuario usuario;
     private Integer contador;
     private Date actualizacion;
     private Byte permiso;
     private Set modalSeguroDeVidas = new HashSet(0);
     private Set modalAsistencias = new HashSet(0);
     private Set modalGastosMedicoses = new HashSet(0);
     private Set modalSeguroDeHogars = new HashSet(0);
     private Set selectorAsistencias = new HashSet(0);
     private Set modalPymes = new HashSet(0);

    public AreaEjecutivo() {
    }

	
    public AreaEjecutivo(int id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public AreaEjecutivo(int id, Area area, Usuario usuario, Integer contador, Date actualizacion, Byte permiso, Set modalSeguroDeVidas, Set modalAsistencias, Set modalGastosMedicoses, Set modalSeguroDeHogars, Set selectorAsistencias, Set modalPymes) {
       this.id = id;
       this.area = area;
       this.usuario = usuario;
       this.contador = contador;
       this.actualizacion = actualizacion;
       this.permiso = permiso;
       this.modalSeguroDeVidas = modalSeguroDeVidas;
       this.modalAsistencias = modalAsistencias;
       this.modalGastosMedicoses = modalGastosMedicoses;
       this.modalSeguroDeHogars = modalSeguroDeHogars;
       this.selectorAsistencias = selectorAsistencias;
       this.modalPymes = modalPymes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idArea")
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="contador")
    public Integer getContador() {
        return this.contador;
    }
    
    public void setContador(Integer contador) {
        this.contador = contador;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="actualizacion", length=19)
    public Date getActualizacion() {
        return this.actualizacion;
    }
    
    public void setActualizacion(Date actualizacion) {
        this.actualizacion = actualizacion;
    }

    
    @Column(name="permiso")
    public Byte getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(Byte permiso) {
        this.permiso = permiso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areaEjecutivo")
    public Set getModalSeguroDeVidas() {
        return this.modalSeguroDeVidas;
    }
    
    public void setModalSeguroDeVidas(Set modalSeguroDeVidas) {
        this.modalSeguroDeVidas = modalSeguroDeVidas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areaEjecutivo")
    public Set getModalAsistencias() {
        return this.modalAsistencias;
    }
    
    public void setModalAsistencias(Set modalAsistencias) {
        this.modalAsistencias = modalAsistencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areaEjecutivo")
    public Set getModalGastosMedicoses() {
        return this.modalGastosMedicoses;
    }
    
    public void setModalGastosMedicoses(Set modalGastosMedicoses) {
        this.modalGastosMedicoses = modalGastosMedicoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areaEjecutivo")
    public Set getModalSeguroDeHogars() {
        return this.modalSeguroDeHogars;
    }
    
    public void setModalSeguroDeHogars(Set modalSeguroDeHogars) {
        this.modalSeguroDeHogars = modalSeguroDeHogars;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areaEjecutivo")
    public Set getSelectorAsistencias() {
        return this.selectorAsistencias;
    }
    
    public void setSelectorAsistencias(Set selectorAsistencias) {
        this.selectorAsistencias = selectorAsistencias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="areaEjecutivo")
    public Set getModalPymes() {
        return this.modalPymes;
    }
    
    public void setModalPymes(Set modalPymes) {
        this.modalPymes = modalPymes;
    }




}


