package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bancos generated by hbm2java
 */
@Entity
@Table(name="bancos"
    ,catalog="trigarante"
)
public class Bancos  implements java.io.Serializable {


     private int id;
     private String banco;
     private Set datosPagos = new HashSet(0);

    public Bancos() {
    }

	
    public Bancos(int id, String banco) {
        this.id = id;
        this.banco = banco;
    }
    public Bancos(int id, String banco, Set datosPagos) {
       this.id = id;
       this.banco = banco;
       this.datosPagos = datosPagos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="banco", nullable=false, length=50)
    public String getBanco() {
        return this.banco;
    }
    
    public void setBanco(String banco) {
        this.banco = banco;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bancos")
    public Set getDatosPagos() {
        return this.datosPagos;
    }
    
    public void setDatosPagos(Set datosPagos) {
        this.datosPagos = datosPagos;
    }




}


