package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Buscador generated by hbm2java
 */
@Entity
@Table(name="buscador"
    ,catalog="trigarante"
)
public class Buscador  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set costoses = new HashSet(0);

    public Buscador() {
    }

	
    public Buscador(int id) {
        this.id = id;
    }
    public Buscador(int id, String descripcion, Set costoses) {
       this.id = id;
       this.descripcion = descripcion;
       this.costoses = costoses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buscador")
    public Set getCostoses() {
        return this.costoses;
    }
    
    public void setCostoses(Set costoses) {
        this.costoses = costoses;
    }




}


