package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Campaña generated by hbm2java
 */
@Entity
@Table(name="campaña"
    ,catalog="trigarante"
)
public class Campaña  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set usuarios = new HashSet(0);
     private Set telefonos = new HashSet(0);
     private Set paginas = new HashSet(0);
     private Set solicituds = new HashSet(0);

    public Campaña() {
    }

	
    public Campaña(int id) {
        this.id = id;
    }
    public Campaña(int id, String nombre, Set usuarios, Set telefonos, Set paginas, Set solicituds) {
       this.id = id;
       this.nombre = nombre;
       this.usuarios = usuarios;
       this.telefonos = telefonos;
       this.paginas = paginas;
       this.solicituds = solicituds;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="campaña")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="campaña")
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="campaña")
    public Set getPaginas() {
        return this.paginas;
    }
    
    public void setPaginas(Set paginas) {
        this.paginas = paginas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="campaña")
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }




}


