package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatalogoDeConceptos generated by hbm2java
 */
@Entity
@Table(name="catalogoDeConceptos"
    ,catalog="trigarante"
)
public class CatalogoDeConceptos  implements java.io.Serializable {


     private int id;
     private int tipo;
     private String descripcion;
     private Set estadoDeCuentas = new HashSet(0);

    public CatalogoDeConceptos() {
    }

	
    public CatalogoDeConceptos(int id, int tipo, String descripcion) {
        this.id = id;
        this.tipo = tipo;
        this.descripcion = descripcion;
    }
    public CatalogoDeConceptos(int id, int tipo, String descripcion, Set estadoDeCuentas) {
       this.id = id;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.estadoDeCuentas = estadoDeCuentas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="tipo", nullable=false)
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="descripcion", nullable=false, length=150)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catalogoDeConceptos")
    public Set getEstadoDeCuentas() {
        return this.estadoDeCuentas;
    }
    
    public void setEstadoDeCuentas(Set estadoDeCuentas) {
        this.estadoDeCuentas = estadoDeCuentas;
    }




}


