package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="trigarante"
)
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String rfc;
     private String password;
     private String nombre;
     private String apPat;
     private String apMat;
     private String correo;
     private int telefono;
     private int telefonoOpc;
     private String correoOpc;
     private Date fechaNac;
     private String nacionalidad;
     private Set registros = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, String rfc, String password, String nombre, String apPat, String apMat, int telefono, int telefonoOpc, Date fechaNac) {
        this.idCliente = idCliente;
        this.rfc = rfc;
        this.password = password;
        this.nombre = nombre;
        this.apPat = apPat;
        this.apMat = apMat;
        this.telefono = telefono;
        this.telefonoOpc = telefonoOpc;
        this.fechaNac = fechaNac;
    }
    public Cliente(int idCliente, String rfc, String password, String nombre, String apPat, String apMat, String correo, int telefono, int telefonoOpc, String correoOpc, Date fechaNac, String nacionalidad, Set registros) {
       this.idCliente = idCliente;
       this.rfc = rfc;
       this.password = password;
       this.nombre = nombre;
       this.apPat = apPat;
       this.apMat = apMat;
       this.correo = correo;
       this.telefono = telefono;
       this.telefonoOpc = telefonoOpc;
       this.correoOpc = correoOpc;
       this.fechaNac = fechaNac;
       this.nacionalidad = nacionalidad;
       this.registros = registros;
    }
   
     @Id 

    
    @Column(name="idCliente", unique=true, nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="rfc", nullable=false, length=13)
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

    
    @Column(name="password", nullable=false, length=25)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apPat", nullable=false, length=50)
    public String getApPat() {
        return this.apPat;
    }
    
    public void setApPat(String apPat) {
        this.apPat = apPat;
    }

    
    @Column(name="apMat", nullable=false, length=50)
    public String getApMat() {
        return this.apMat;
    }
    
    public void setApMat(String apMat) {
        this.apMat = apMat;
    }

    
    @Column(name="correo", length=100)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="telefono", nullable=false)
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="telefono_opc", nullable=false)
    public int getTelefonoOpc() {
        return this.telefonoOpc;
    }
    
    public void setTelefonoOpc(int telefonoOpc) {
        this.telefonoOpc = telefonoOpc;
    }

    
    @Column(name="correo_opc", length=50)
    public String getCorreoOpc() {
        return this.correoOpc;
    }
    
    public void setCorreoOpc(String correoOpc) {
        this.correoOpc = correoOpc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaNac", nullable=false, length=10)
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }

    
    @Column(name="nacionalidad", length=30)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


