package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Costos generated by hbm2java
 */
@Entity
@Table(name="costos"
    ,catalog="trigarante"
)
public class Costos  implements java.io.Serializable {


     private int id;
     private Buscador buscador;
     private Pagina pagina;
     private Date fecha;
     private BigDecimal costo;
     private int conversiones;

    public Costos() {
    }

    public Costos(int id, Buscador buscador, Pagina pagina, Date fecha, BigDecimal costo, int conversiones) {
       this.id = id;
       this.buscador = buscador;
       this.pagina = pagina;
       this.fecha = fecha;
       this.costo = costo;
       this.conversiones = conversiones;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idBuscador", nullable=false)
    public Buscador getBuscador() {
        return this.buscador;
    }
    
    public void setBuscador(Buscador buscador) {
        this.buscador = buscador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPagina", nullable=false)
    public Pagina getPagina() {
        return this.pagina;
    }
    
    public void setPagina(Pagina pagina) {
        this.pagina = pagina;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="costo", nullable=false, precision=10)
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    
    @Column(name="conversiones", nullable=false)
    public int getConversiones() {
        return this.conversiones;
    }
    
    public void setConversiones(int conversiones) {
        this.conversiones = conversiones;
    }




}


