package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Endoso generated by hbm2java
 */
@Entity
@Table(name="endoso"
    ,catalog="trigarante"
)
public class Endoso  implements java.io.Serializable {


     private Integer idEndoso;
     private EstadoNomina estadoNomina;
     private TipoEndoso tipoEndoso;
     private Usuario usuario;
     private BigDecimal cantidad;
     private Date fecha;
     private Date fechaEndoso;
     private String numPoliza;
     private Date fechaInicio;
     private Byte idAseguradora;
     private String descripcionEndoso;
     private int idNomina;

    public Endoso() {
    }

	
    public Endoso(EstadoNomina estadoNomina, Usuario usuario, BigDecimal cantidad, Date fecha, Date fechaEndoso, String descripcionEndoso, int idNomina) {
        this.estadoNomina = estadoNomina;
        this.usuario = usuario;
        this.cantidad = cantidad;
        this.fecha = fecha;
        this.fechaEndoso = fechaEndoso;
        this.descripcionEndoso = descripcionEndoso;
        this.idNomina = idNomina;
    }
    public Endoso(EstadoNomina estadoNomina, TipoEndoso tipoEndoso, Usuario usuario, BigDecimal cantidad, Date fecha, Date fechaEndoso, String numPoliza, Date fechaInicio, Byte idAseguradora, String descripcionEndoso, int idNomina) {
       this.estadoNomina = estadoNomina;
       this.tipoEndoso = tipoEndoso;
       this.usuario = usuario;
       this.cantidad = cantidad;
       this.fecha = fecha;
       this.fechaEndoso = fechaEndoso;
       this.numPoliza = numPoliza;
       this.fechaInicio = fechaInicio;
       this.idAseguradora = idAseguradora;
       this.descripcionEndoso = descripcionEndoso;
       this.idNomina = idNomina;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEndoso", unique=true, nullable=false)
    public Integer getIdEndoso() {
        return this.idEndoso;
    }
    
    public void setIdEndoso(Integer idEndoso) {
        this.idEndoso = idEndoso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoNomina", nullable=false)
    public EstadoNomina getEstadoNomina() {
        return this.estadoNomina;
    }
    
    public void setEstadoNomina(EstadoNomina estadoNomina) {
        this.estadoNomina = estadoNomina;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoEndoso")
    public TipoEndoso getTipoEndoso() {
        return this.tipoEndoso;
    }
    
    public void setTipoEndoso(TipoEndoso tipoEndoso) {
        this.tipoEndoso = tipoEndoso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="cantidad", nullable=false, precision=10)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaEndoso", nullable=false, length=10)
    public Date getFechaEndoso() {
        return this.fechaEndoso;
    }
    
    public void setFechaEndoso(Date fechaEndoso) {
        this.fechaEndoso = fechaEndoso;
    }

    
    @Column(name="numPoliza", length=50)
    public String getNumPoliza() {
        return this.numPoliza;
    }
    
    public void setNumPoliza(String numPoliza) {
        this.numPoliza = numPoliza;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaInicio", length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    
    @Column(name="idAseguradora")
    public Byte getIdAseguradora() {
        return this.idAseguradora;
    }
    
    public void setIdAseguradora(Byte idAseguradora) {
        this.idAseguradora = idAseguradora;
    }

    
    @Column(name="descripcionEndoso", nullable=false, length=65535)
    public String getDescripcionEndoso() {
        return this.descripcionEndoso;
    }
    
    public void setDescripcionEndoso(String descripcionEndoso) {
        this.descripcionEndoso = descripcionEndoso;
    }

    
    @Column(name="idNomina", nullable=false)
    public int getIdNomina() {
        return this.idNomina;
    }
    
    public void setIdNomina(int idNomina) {
        this.idNomina = idNomina;
    }




}


