package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoNomina generated by hbm2java
 */
@Entity
@Table(name="estadoNomina"
    ,catalog="trigarante"
)
public class EstadoNomina  implements java.io.Serializable {


     private int id;
     private String estado;
     private Set pagos = new HashSet(0);
     private Set endosos = new HashSet(0);

    public EstadoNomina() {
    }

	
    public EstadoNomina(int id, String estado) {
        this.id = id;
        this.estado = estado;
    }
    public EstadoNomina(int id, String estado, Set pagos, Set endosos) {
       this.id = id;
       this.estado = estado;
       this.pagos = pagos;
       this.endosos = endosos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="estado", nullable=false, length=30)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoNomina")
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoNomina")
    public Set getEndosos() {
        return this.endosos;
    }
    
    public void setEndosos(Set endosos) {
        this.endosos = endosos;
    }




}


