package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoAsistencia generated by hbm2java
 */
@Entity
@Table(name="estadoAsistencia"
    ,catalog="trigarante"
)
public class EstadoAsistencia  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set asistencias = new HashSet(0);

    public EstadoAsistencia() {
    }

	
    public EstadoAsistencia(int id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }
    public EstadoAsistencia(int id, String descripcion, Set asistencias) {
       this.id = id;
       this.descripcion = descripcion;
       this.asistencias = asistencias;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoAsistencia")
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }




}


