package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoSolicitud generated by hbm2java
 */
@Entity
@Table(name="estadoSolicitud"
    ,catalog="trigarante"
)
public class EstadoSolicitud  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set solicituds = new HashSet(0);

    public EstadoSolicitud() {
    }

	
    public EstadoSolicitud(int id) {
        this.id = id;
    }
    public EstadoSolicitud(int id, String descripcion, Set solicituds) {
       this.id = id;
       this.descripcion = descripcion;
       this.solicituds = solicituds;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estadoSolicitud")
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }




}


