package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Nomina generated by hbm2java
 */
@Entity
@Table(name="nomina"
    ,catalog="trigarante"
)
public class Nomina  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private Date fechaPago;
     private BigDecimal garantizado;
     private BigDecimal ajustes;
     private int modulos;
     private int asistencias;
     private BigDecimal totalPagado;
     private String comentarios;
     private Set pagos = new HashSet(0);

    public Nomina() {
    }

	
    public Nomina(int id, Usuario usuario, Date fechaPago, BigDecimal garantizado, BigDecimal ajustes, int modulos, int asistencias, BigDecimal totalPagado) {
        this.id = id;
        this.usuario = usuario;
        this.fechaPago = fechaPago;
        this.garantizado = garantizado;
        this.ajustes = ajustes;
        this.modulos = modulos;
        this.asistencias = asistencias;
        this.totalPagado = totalPagado;
    }
    public Nomina(int id, Usuario usuario, Date fechaPago, BigDecimal garantizado, BigDecimal ajustes, int modulos, int asistencias, BigDecimal totalPagado, String comentarios, Set pagos) {
       this.id = id;
       this.usuario = usuario;
       this.fechaPago = fechaPago;
       this.garantizado = garantizado;
       this.ajustes = ajustes;
       this.modulos = modulos;
       this.asistencias = asistencias;
       this.totalPagado = totalPagado;
       this.comentarios = comentarios;
       this.pagos = pagos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaPago", nullable=false, length=19)
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    
    @Column(name="garantizado", nullable=false, precision=10)
    public BigDecimal getGarantizado() {
        return this.garantizado;
    }
    
    public void setGarantizado(BigDecimal garantizado) {
        this.garantizado = garantizado;
    }

    
    @Column(name="ajustes", nullable=false, precision=10)
    public BigDecimal getAjustes() {
        return this.ajustes;
    }
    
    public void setAjustes(BigDecimal ajustes) {
        this.ajustes = ajustes;
    }

    
    @Column(name="modulos", nullable=false)
    public int getModulos() {
        return this.modulos;
    }
    
    public void setModulos(int modulos) {
        this.modulos = modulos;
    }

    
    @Column(name="asistencias", nullable=false)
    public int getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(int asistencias) {
        this.asistencias = asistencias;
    }

    
    @Column(name="totalPagado", nullable=false, precision=10)
    public BigDecimal getTotalPagado() {
        return this.totalPagado;
    }
    
    public void setTotalPagado(BigDecimal totalPagado) {
        this.totalPagado = totalPagado;
    }

    
    @Column(name="comentarios", length=50)
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nomina")
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }




}


