package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SelectorAsistencia generated by hbm2java
 */
@Entity
@Table(name="selectorAsistencia"
    ,catalog="trigarante"
)
public class SelectorAsistencia  implements java.io.Serializable {


     private int id;
     private AreaEjecutivo areaEjecutivo;
     private int contador;
     private Date actualizacion;
     private int permiso;

    public SelectorAsistencia() {
    }

    public SelectorAsistencia(int id, AreaEjecutivo areaEjecutivo, int contador, Date actualizacion, int permiso) {
       this.id = id;
       this.areaEjecutivo = areaEjecutivo;
       this.contador = contador;
       this.actualizacion = actualizacion;
       this.permiso = permiso;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario", nullable=false)
    public AreaEjecutivo getAreaEjecutivo() {
        return this.areaEjecutivo;
    }
    
    public void setAreaEjecutivo(AreaEjecutivo areaEjecutivo) {
        this.areaEjecutivo = areaEjecutivo;
    }

    
    @Column(name="contador", nullable=false)
    public int getContador() {
        return this.contador;
    }
    
    public void setContador(int contador) {
        this.contador = contador;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="actualizacion", nullable=false, length=19)
    public Date getActualizacion() {
        return this.actualizacion;
    }
    
    public void setActualizacion(Date actualizacion) {
        this.actualizacion = actualizacion;
    }

    
    @Column(name="permiso", nullable=false)
    public int getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(int permiso) {
        this.permiso = permiso;
    }




}


