package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefono generated by hbm2java
 */
@Entity
@Table(name="telefono"
    ,catalog="trigarante"
)
public class Telefono  implements java.io.Serializable {


     private int id;
     private Campaña campaña;
     private String numero;

    public Telefono() {
    }

    public Telefono(int id, Campaña campaña, String numero) {
       this.id = id;
       this.campaña = campaña;
       this.numero = numero;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCampaña", nullable=false)
    public Campaña getCampaña() {
        return this.campaña;
    }
    
    public void setCampaña(Campaña campaña) {
        this.campaña = campaña;
    }

    
    @Column(name="numero", nullable=false, length=50)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }




}


