package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEgreso generated by hbm2java
 */
@Entity
@Table(name="tipoEgreso"
    ,catalog="trigarante"
)
public class TipoEgreso  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set estadoDeCuentas = new HashSet(0);

    public TipoEgreso() {
    }

	
    public TipoEgreso(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public TipoEgreso(int id, String nombre, Set estadoDeCuentas) {
       this.id = id;
       this.nombre = nombre;
       this.estadoDeCuentas = estadoDeCuentas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoEgreso")
    public Set getEstadoDeCuentas() {
        return this.estadoDeCuentas;
    }
    
    public void setEstadoDeCuentas(Set estadoDeCuentas) {
        this.estadoDeCuentas = estadoDeCuentas;
    }




}


