package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPago generated by hbm2java
 */
@Entity
@Table(name="tipoPago"
    ,catalog="trigarante"
)
public class TipoPago  implements java.io.Serializable {


     private int id;
     private String tipo;
     private int cantidadPagos;
     private Set registros = new HashSet(0);

    public TipoPago() {
    }

	
    public TipoPago(int id, String tipo, int cantidadPagos) {
        this.id = id;
        this.tipo = tipo;
        this.cantidadPagos = cantidadPagos;
    }
    public TipoPago(int id, String tipo, int cantidadPagos, Set registros) {
       this.id = id;
       this.tipo = tipo;
       this.cantidadPagos = cantidadPagos;
       this.registros = registros;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="tipo", nullable=false, length=50)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="cantidadPagos", nullable=false)
    public int getCantidadPagos() {
        return this.cantidadPagos;
    }
    
    public void setCantidadPagos(int cantidadPagos) {
        this.cantidadPagos = cantidadPagos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoPago")
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


