package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPoliza generated by hbm2java
 */
@Entity
@Table(name="tipoPoliza"
    ,catalog="trigarante"
)
public class TipoPoliza  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set registros = new HashSet(0);

    public TipoPoliza() {
    }

	
    public TipoPoliza(int id) {
        this.id = id;
    }
    public TipoPoliza(int id, String descripcion, Set registros) {
       this.id = id;
       this.descripcion = descripcion;
       this.registros = registros;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoPoliza")
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


