package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ucis generated by hbm2java
 */
@Entity
@Table(name="UCIS"
    ,catalog="trigarante"
)
public class Ucis  implements java.io.Serializable {


     private int id;
     private Usuario usuarioByActualizadoPor;
     private Usuario usuarioByIdUsuario;
     private Usuario usuarioByAsignadoPor;
     private String passwordPersonal;
     private Date fechaCreacion;
     private Date fechaActualizacion;
     private String descripcion;

    public Ucis() {
    }

	
    public Ucis(int id, Usuario usuarioByActualizadoPor, Usuario usuarioByIdUsuario, Usuario usuarioByAsignadoPor, Date fechaCreacion, Date fechaActualizacion) {
        this.id = id;
        this.usuarioByActualizadoPor = usuarioByActualizadoPor;
        this.usuarioByIdUsuario = usuarioByIdUsuario;
        this.usuarioByAsignadoPor = usuarioByAsignadoPor;
        this.fechaCreacion = fechaCreacion;
        this.fechaActualizacion = fechaActualizacion;
    }
    public Ucis(int id, Usuario usuarioByActualizadoPor, Usuario usuarioByIdUsuario, Usuario usuarioByAsignadoPor, String passwordPersonal, Date fechaCreacion, Date fechaActualizacion, String descripcion) {
       this.id = id;
       this.usuarioByActualizadoPor = usuarioByActualizadoPor;
       this.usuarioByIdUsuario = usuarioByIdUsuario;
       this.usuarioByAsignadoPor = usuarioByAsignadoPor;
       this.passwordPersonal = passwordPersonal;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
       this.descripcion = descripcion;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="actualizadoPor", nullable=false)
    public Usuario getUsuarioByActualizadoPor() {
        return this.usuarioByActualizadoPor;
    }
    
    public void setUsuarioByActualizadoPor(Usuario usuarioByActualizadoPor) {
        this.usuarioByActualizadoPor = usuarioByActualizadoPor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario", nullable=false)
    public Usuario getUsuarioByIdUsuario() {
        return this.usuarioByIdUsuario;
    }
    
    public void setUsuarioByIdUsuario(Usuario usuarioByIdUsuario) {
        this.usuarioByIdUsuario = usuarioByIdUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="asignadoPor", nullable=false)
    public Usuario getUsuarioByAsignadoPor() {
        return this.usuarioByAsignadoPor;
    }
    
    public void setUsuarioByAsignadoPor(Usuario usuarioByAsignadoPor) {
        this.usuarioByAsignadoPor = usuarioByAsignadoPor;
    }

    
    @Column(name="passwordPersonal", length=50)
    public String getPasswordPersonal() {
        return this.passwordPersonal;
    }
    
    public void setPasswordPersonal(String passwordPersonal) {
        this.passwordPersonal = passwordPersonal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaCreacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaActualizacion", nullable=false, length=19)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


