package model;
// Generated May 20, 2016 1:01:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuarioVip generated by hbm2java
 */
@Entity
@Table(name="usuarioVIP"
    ,catalog="trigarante"
)
public class UsuarioVip  implements java.io.Serializable {


     private int id;
     private Usuario usuarioByIdUsuario;
     private Usuario usuarioByModificadoPor;
     private int estado;
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public UsuarioVip() {
    }

	
    public UsuarioVip(int id, int estado, Date fechaCreacion, Date fechaModificacion) {
        this.id = id;
        this.estado = estado;
        this.fechaCreacion = fechaCreacion;
        this.fechaModificacion = fechaModificacion;
    }
    public UsuarioVip(int id, Usuario usuarioByIdUsuario, Usuario usuarioByModificadoPor, int estado, String descripcion, Date fechaCreacion, Date fechaModificacion) {
       this.id = id;
       this.usuarioByIdUsuario = usuarioByIdUsuario;
       this.usuarioByModificadoPor = usuarioByModificadoPor;
       this.estado = estado;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuario")
    public Usuario getUsuarioByIdUsuario() {
        return this.usuarioByIdUsuario;
    }
    
    public void setUsuarioByIdUsuario(Usuario usuarioByIdUsuario) {
        this.usuarioByIdUsuario = usuarioByIdUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modificadoPor")
    public Usuario getUsuarioByModificadoPor() {
        return this.usuarioByModificadoPor;
    }
    
    public void setUsuarioByModificadoPor(Usuario usuarioByModificadoPor) {
        this.usuarioByModificadoPor = usuarioByModificadoPor;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaCreacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaModificacion", nullable=false, length=19)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


