package model;
// Generated May 23, 2016 10:25:24 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AreaEjecutivo generated by hbm2java
 */
public class AreaEjecutivo  implements java.io.Serializable {


     private int id;
     private Area area;
     private Usuario usuario;
     private Integer contador;
     private Date actualizacion;
     private Byte permiso;
     private Set modalSeguroDeVidas = new HashSet(0);
     private Set modalAsistencias = new HashSet(0);
     private Set modalGastosMedicoses = new HashSet(0);
     private Set modalSeguroDeHogars = new HashSet(0);
     private Set selectorAsistencias = new HashSet(0);
     private Set modalPymes = new HashSet(0);

    public AreaEjecutivo() {
    }

	
    public AreaEjecutivo(int id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public AreaEjecutivo(int id, Area area, Usuario usuario, Integer contador, Date actualizacion, Byte permiso, Set modalSeguroDeVidas, Set modalAsistencias, Set modalGastosMedicoses, Set modalSeguroDeHogars, Set selectorAsistencias, Set modalPymes) {
       this.id = id;
       this.area = area;
       this.usuario = usuario;
       this.contador = contador;
       this.actualizacion = actualizacion;
       this.permiso = permiso;
       this.modalSeguroDeVidas = modalSeguroDeVidas;
       this.modalAsistencias = modalAsistencias;
       this.modalGastosMedicoses = modalGastosMedicoses;
       this.modalSeguroDeHogars = modalSeguroDeHogars;
       this.selectorAsistencias = selectorAsistencias;
       this.modalPymes = modalPymes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getContador() {
        return this.contador;
    }
    
    public void setContador(Integer contador) {
        this.contador = contador;
    }
    public Date getActualizacion() {
        return this.actualizacion;
    }
    
    public void setActualizacion(Date actualizacion) {
        this.actualizacion = actualizacion;
    }
    public Byte getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(Byte permiso) {
        this.permiso = permiso;
    }
    public Set getModalSeguroDeVidas() {
        return this.modalSeguroDeVidas;
    }
    
    public void setModalSeguroDeVidas(Set modalSeguroDeVidas) {
        this.modalSeguroDeVidas = modalSeguroDeVidas;
    }
    public Set getModalAsistencias() {
        return this.modalAsistencias;
    }
    
    public void setModalAsistencias(Set modalAsistencias) {
        this.modalAsistencias = modalAsistencias;
    }
    public Set getModalGastosMedicoses() {
        return this.modalGastosMedicoses;
    }
    
    public void setModalGastosMedicoses(Set modalGastosMedicoses) {
        this.modalGastosMedicoses = modalGastosMedicoses;
    }
    public Set getModalSeguroDeHogars() {
        return this.modalSeguroDeHogars;
    }
    
    public void setModalSeguroDeHogars(Set modalSeguroDeHogars) {
        this.modalSeguroDeHogars = modalSeguroDeHogars;
    }
    public Set getSelectorAsistencias() {
        return this.selectorAsistencias;
    }
    
    public void setSelectorAsistencias(Set selectorAsistencias) {
        this.selectorAsistencias = selectorAsistencias;
    }
    public Set getModalPymes() {
        return this.modalPymes;
    }
    
    public void setModalPymes(Set modalPymes) {
        this.modalPymes = modalPymes;
    }




}


