package model;
// Generated May 23, 2016 10:25:24 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EstadoRenovacion generated by hbm2java
 */
public class EstadoRenovacion  implements java.io.Serializable {


     private int id;
     private String estado;
     private Set registros = new HashSet(0);

    public EstadoRenovacion() {
    }

	
    public EstadoRenovacion(int id) {
        this.id = id;
    }
    public EstadoRenovacion(int id, String estado, Set registros) {
       this.id = id;
       this.estado = estado;
       this.registros = registros;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


