package model;
// Generated May 23, 2016 10:25:24 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ModalSeguroDeVida generated by hbm2java
 */
public class ModalSeguroDeVida  implements java.io.Serializable {


     private int id;
     private AreaEjecutivo areaEjecutivo;
     private Solicitud solicitud;
     private String sexo;
     private BigDecimal sumaAseguradora;

    public ModalSeguroDeVida() {
    }

    public ModalSeguroDeVida(int id, AreaEjecutivo areaEjecutivo, Solicitud solicitud, String sexo, BigDecimal sumaAseguradora) {
       this.id = id;
       this.areaEjecutivo = areaEjecutivo;
       this.solicitud = solicitud;
       this.sexo = sexo;
       this.sumaAseguradora = sumaAseguradora;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public AreaEjecutivo getAreaEjecutivo() {
        return this.areaEjecutivo;
    }
    
    public void setAreaEjecutivo(AreaEjecutivo areaEjecutivo) {
        this.areaEjecutivo = areaEjecutivo;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public BigDecimal getSumaAseguradora() {
        return this.sumaAseguradora;
    }
    
    public void setSumaAseguradora(BigDecimal sumaAseguradora) {
        this.sumaAseguradora = sumaAseguradora;
    }




}


