package model;
// Generated May 23, 2016 10:25:24 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoEndoso generated by hbm2java
 */
public class TipoEndoso  implements java.io.Serializable {


     private int id;
     private String tipo;
     private Set endosos = new HashSet(0);

    public TipoEndoso() {
    }

	
    public TipoEndoso(int id) {
        this.id = id;
    }
    public TipoEndoso(int id, String tipo, Set endosos) {
       this.id = id;
       this.tipo = tipo;
       this.endosos = endosos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getEndosos() {
        return this.endosos;
    }
    
    public void setEndosos(Set endosos) {
        this.endosos = endosos;
    }




}


