package models;
// Generated May 17, 2016 9:49:25 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private String nombre;
     private Set areaEjecutivos = new HashSet(0);
     private Set estadoDeCuentas = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Area() {
    }

	
    public Area(int id, String descripcion, String nombre) {
        this.id = id;
        this.descripcion = descripcion;
        this.nombre = nombre;
    }
    public Area(int id, String descripcion, String nombre, Set areaEjecutivos, Set estadoDeCuentas, Set usuarios) {
       this.id = id;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.areaEjecutivos = areaEjecutivos;
       this.estadoDeCuentas = estadoDeCuentas;
       this.usuarios = usuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAreaEjecutivos() {
        return this.areaEjecutivos;
    }
    
    public void setAreaEjecutivos(Set areaEjecutivos) {
        this.areaEjecutivos = areaEjecutivos;
    }
    public Set getEstadoDeCuentas() {
        return this.estadoDeCuentas;
    }
    
    public void setEstadoDeCuentas(Set estadoDeCuentas) {
        this.estadoDeCuentas = estadoDeCuentas;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


