package models;
// Generated May 17, 2016 9:49:25 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Buscador generated by hbm2java
 */
public class Buscador  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Set costoses = new HashSet(0);

    public Buscador() {
    }

	
    public Buscador(int id) {
        this.id = id;
    }
    public Buscador(int id, String descripcion, Set costoses) {
       this.id = id;
       this.descripcion = descripcion;
       this.costoses = costoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCostoses() {
        return this.costoses;
    }
    
    public void setCostoses(Set costoses) {
        this.costoses = costoses;
    }




}


