package models;
// Generated May 17, 2016 9:49:25 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Campaña generated by hbm2java
 */
public class Campaña  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set usuarios = new HashSet(0);
     private Set telefonos = new HashSet(0);
     private Set paginas = new HashSet(0);
     private Set solicituds = new HashSet(0);

    public Campaña() {
    }

	
    public Campaña(int id) {
        this.id = id;
    }
    public Campaña(int id, String nombre, Set usuarios, Set telefonos, Set paginas, Set solicituds) {
       this.id = id;
       this.nombre = nombre;
       this.usuarios = usuarios;
       this.telefonos = telefonos;
       this.paginas = paginas;
       this.solicituds = solicituds;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }
    public Set getPaginas() {
        return this.paginas;
    }
    
    public void setPaginas(Set paginas) {
        this.paginas = paginas;
    }
    public Set getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set solicituds) {
        this.solicituds = solicituds;
    }




}


