package models;
// Generated May 17, 2016 9:49:25 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EstadoDeCuenta generated by hbm2java
 */
public class EstadoDeCuenta  implements java.io.Serializable {


     private int id;
     private Area area;
     private CatalogoDeConceptos catalogoDeConceptos;
     private TipoEgreso tipoEgreso;
     private Date fecha;
     private Integer tipo;
     private String descripcion;
     private Float monto;
     private Integer idAseguradora;

    public EstadoDeCuenta() {
    }

	
    public EstadoDeCuenta(int id) {
        this.id = id;
    }
    public EstadoDeCuenta(int id, Area area, CatalogoDeConceptos catalogoDeConceptos, TipoEgreso tipoEgreso, Date fecha, Integer tipo, String descripcion, Float monto, Integer idAseguradora) {
       this.id = id;
       this.area = area;
       this.catalogoDeConceptos = catalogoDeConceptos;
       this.tipoEgreso = tipoEgreso;
       this.fecha = fecha;
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.monto = monto;
       this.idAseguradora = idAseguradora;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public CatalogoDeConceptos getCatalogoDeConceptos() {
        return this.catalogoDeConceptos;
    }
    
    public void setCatalogoDeConceptos(CatalogoDeConceptos catalogoDeConceptos) {
        this.catalogoDeConceptos = catalogoDeConceptos;
    }
    public TipoEgreso getTipoEgreso() {
        return this.tipoEgreso;
    }
    
    public void setTipoEgreso(TipoEgreso tipoEgreso) {
        this.tipoEgreso = tipoEgreso;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getMonto() {
        return this.monto;
    }
    
    public void setMonto(Float monto) {
        this.monto = monto;
    }
    public Integer getIdAseguradora() {
        return this.idAseguradora;
    }
    
    public void setIdAseguradora(Integer idAseguradora) {
        this.idAseguradora = idAseguradora;
    }




}


