package models;
// Generated May 17, 2016 9:49:25 AM by Hibernate Tools 4.3.1



/**
 * Ranking generated by hbm2java
 */
public class Ranking  implements java.io.Serializable {


     private int idRaking;
     private Usuario usuario;
     private Integer rol;
     private Integer mes;
     private Integer semana1;
     private Integer semana2;
     private Integer semana3;
     private Integer semana4;
     private Integer semana5;

    public Ranking() {
    }

	
    public Ranking(int idRaking) {
        this.idRaking = idRaking;
    }
    public Ranking(int idRaking, Usuario usuario, Integer rol, Integer mes, Integer semana1, Integer semana2, Integer semana3, Integer semana4, Integer semana5) {
       this.idRaking = idRaking;
       this.usuario = usuario;
       this.rol = rol;
       this.mes = mes;
       this.semana1 = semana1;
       this.semana2 = semana2;
       this.semana3 = semana3;
       this.semana4 = semana4;
       this.semana5 = semana5;
    }
   
    public int getIdRaking() {
        return this.idRaking;
    }
    
    public void setIdRaking(int idRaking) {
        this.idRaking = idRaking;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getRol() {
        return this.rol;
    }
    
    public void setRol(Integer rol) {
        this.rol = rol;
    }
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }
    public Integer getSemana1() {
        return this.semana1;
    }
    
    public void setSemana1(Integer semana1) {
        this.semana1 = semana1;
    }
    public Integer getSemana2() {
        return this.semana2;
    }
    
    public void setSemana2(Integer semana2) {
        this.semana2 = semana2;
    }
    public Integer getSemana3() {
        return this.semana3;
    }
    
    public void setSemana3(Integer semana3) {
        this.semana3 = semana3;
    }
    public Integer getSemana4() {
        return this.semana4;
    }
    
    public void setSemana4(Integer semana4) {
        this.semana4 = semana4;
    }
    public Integer getSemana5() {
        return this.semana5;
    }
    
    public void setSemana5(Integer semana5) {
        this.semana5 = semana5;
    }




}


