package models;
// Generated May 17, 2016 9:49:25 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoEgreso generated by hbm2java
 */
public class TipoEgreso  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set estadoDeCuentas = new HashSet(0);

    public TipoEgreso() {
    }

	
    public TipoEgreso(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public TipoEgreso(int id, String nombre, Set estadoDeCuentas) {
       this.id = id;
       this.nombre = nombre;
       this.estadoDeCuentas = estadoDeCuentas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEstadoDeCuentas() {
        return this.estadoDeCuentas;
    }
    
    public void setEstadoDeCuentas(Set estadoDeCuentas) {
        this.estadoDeCuentas = estadoDeCuentas;
    }




}


